"""initial tables

Revision ID: 475db3b24576
Revises: 65a6568311e5
Create Date: 2026-03-11 00:46:44.428140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '475db3b24576'
down_revision: Union[str, Sequence[str], None] = '65a6568311e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('inventory_items_product_id_fkey'), 'inventory_items', type_='foreignkey')
    op.create_foreign_key(None, 'inventory_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('products', 'price_cents',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.alter_column('products', 'price_cents',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_constraint(None, 'inventory_items', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_items_product_id_fkey'), 'inventory_items', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
